/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Mon Nov  6 15:45:23 2017. */

#ifndef PB_CONTOSO_PB_H_INCLUDED
#define PB_CONTOSO_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _EventMessage {
    uint32_t Version;
    double WindSpeed;
/* @@protoc_insertion_point(struct:EventMessage) */
} EventMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define EventMessage_init_default                {0, 0}
#define EventMessage_init_zero                   {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define EventMessage_Version_tag                 1
#define EventMessage_WindSpeed_tag               2

/* Struct field encoding specification for nanopb */
extern const pb_field_t EventMessage_fields[3];

/* Maximum encoded size of messages (where known) */
#define EventMessage_size                        15

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define CONTOSO_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
