/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Mon Nov  6 15:45:23 2017. */

#include "contoso.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t EventMessage_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, EventMessage, Version, Version, 0),
    PB_FIELD(  2, DOUBLE  , REQUIRED, STATIC  , OTHER, EventMessage, WindSpeed, Version, 0),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
